version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ../app:/app
      - ../data:/data
    env_file:
      - ../app/.env  
    depends_on:
      db:
        condition: service_healthy
    networks:
      - stock-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=stock_user
      - POSTGRES_PASSWORD=stock_password
      - POSTGRES_DB=stock_db
    ports:
      - "5432:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stock_user -d stock_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - stock-network

volumes:
  postgres-data:

networks:
  stock-network:
    driver: bridge